// Code generated by ent, DO NOT EDIT.

package price

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the price type in the database.
	Label = "price"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldService holds the string denoting the service field in the database.
	FieldService = "service"
	// FieldResourceType holds the string denoting the resource_type field in the database.
	FieldResourceType = "resource_type"
	// FieldRegion holds the string denoting the region field in the database.
	FieldRegion = "region"
	// FieldPriceModel holds the string denoting the price_model field in the database.
	FieldPriceModel = "price_model"
	// FieldPricePerHour holds the string denoting the price_per_hour field in the database.
	FieldPricePerHour = "price_per_hour"
	// FieldUpfrontCost holds the string denoting the upfront_cost field in the database.
	FieldUpfrontCost = "upfront_cost"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldLastUpdatedAt holds the string denoting the last_updated_at field in the database.
	FieldLastUpdatedAt = "last_updated_at"
	// Table holds the table name of the price in the database.
	Table = "prices"
)

// Columns holds all SQL columns for price fields.
var Columns = []string{
	FieldID,
	FieldProvider,
	FieldService,
	FieldResourceType,
	FieldRegion,
	FieldPriceModel,
	FieldPricePerHour,
	FieldUpfrontCost,
	FieldCurrency,
	FieldLastUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// DefaultLastUpdatedAt holds the default value on creation for the "last_updated_at" field.
	DefaultLastUpdatedAt func() time.Time
	// UpdateDefaultLastUpdatedAt holds the default value on update for the "last_updated_at" field.
	UpdateDefaultLastUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Price queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByService orders the results by the service field.
func ByService(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldService, opts...).ToFunc()
}

// ByResourceType orders the results by the resource_type field.
func ByResourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceType, opts...).ToFunc()
}

// ByRegion orders the results by the region field.
func ByRegion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegion, opts...).ToFunc()
}

// ByPriceModel orders the results by the price_model field.
func ByPriceModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriceModel, opts...).ToFunc()
}

// ByPricePerHour orders the results by the price_per_hour field.
func ByPricePerHour(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPricePerHour, opts...).ToFunc()
}

// ByUpfrontCost orders the results by the upfront_cost field.
func ByUpfrontCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpfrontCost, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByLastUpdatedAt orders the results by the last_updated_at field.
func ByLastUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUpdatedAt, opts...).ToFunc()
}
