// Code generated by ent, DO NOT EDIT.

package price

import (
	"priceyy/api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Price {
	return predicate.Price(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Price {
	return predicate.Price(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Price {
	return predicate.Price(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Price {
	return predicate.Price(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Price {
	return predicate.Price(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Price {
	return predicate.Price(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Price {
	return predicate.Price(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Price {
	return predicate.Price(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Price {
	return predicate.Price(sql.FieldLTE(FieldID, id))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.Price {
	return predicate.Price(sql.FieldEQ(FieldProvider, v))
}

// Service applies equality check predicate on the "service" field. It's identical to ServiceEQ.
func Service(v string) predicate.Price {
	return predicate.Price(sql.FieldEQ(FieldService, v))
}

// ResourceType applies equality check predicate on the "resource_type" field. It's identical to ResourceTypeEQ.
func ResourceType(v string) predicate.Price {
	return predicate.Price(sql.FieldEQ(FieldResourceType, v))
}

// Region applies equality check predicate on the "region" field. It's identical to RegionEQ.
func Region(v string) predicate.Price {
	return predicate.Price(sql.FieldEQ(FieldRegion, v))
}

// PriceModel applies equality check predicate on the "price_model" field. It's identical to PriceModelEQ.
func PriceModel(v string) predicate.Price {
	return predicate.Price(sql.FieldEQ(FieldPriceModel, v))
}

// PricePerUnit applies equality check predicate on the "price_per_unit" field. It's identical to PricePerUnitEQ.
func PricePerUnit(v float64) predicate.Price {
	return predicate.Price(sql.FieldEQ(FieldPricePerUnit, v))
}

// UnitOfMeasure applies equality check predicate on the "unit_of_measure" field. It's identical to UnitOfMeasureEQ.
func UnitOfMeasure(v string) predicate.Price {
	return predicate.Price(sql.FieldEQ(FieldUnitOfMeasure, v))
}

// UpfrontCost applies equality check predicate on the "upfront_cost" field. It's identical to UpfrontCostEQ.
func UpfrontCost(v float64) predicate.Price {
	return predicate.Price(sql.FieldEQ(FieldUpfrontCost, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.Price {
	return predicate.Price(sql.FieldEQ(FieldCurrency, v))
}

// LastUpdatedAt applies equality check predicate on the "last_updated_at" field. It's identical to LastUpdatedAtEQ.
func LastUpdatedAt(v time.Time) predicate.Price {
	return predicate.Price(sql.FieldEQ(FieldLastUpdatedAt, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.Price {
	return predicate.Price(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.Price {
	return predicate.Price(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.Price {
	return predicate.Price(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.Price {
	return predicate.Price(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.Price {
	return predicate.Price(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.Price {
	return predicate.Price(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.Price {
	return predicate.Price(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.Price {
	return predicate.Price(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.Price {
	return predicate.Price(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.Price {
	return predicate.Price(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.Price {
	return predicate.Price(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.Price {
	return predicate.Price(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.Price {
	return predicate.Price(sql.FieldContainsFold(FieldProvider, v))
}

// ServiceEQ applies the EQ predicate on the "service" field.
func ServiceEQ(v string) predicate.Price {
	return predicate.Price(sql.FieldEQ(FieldService, v))
}

// ServiceNEQ applies the NEQ predicate on the "service" field.
func ServiceNEQ(v string) predicate.Price {
	return predicate.Price(sql.FieldNEQ(FieldService, v))
}

// ServiceIn applies the In predicate on the "service" field.
func ServiceIn(vs ...string) predicate.Price {
	return predicate.Price(sql.FieldIn(FieldService, vs...))
}

// ServiceNotIn applies the NotIn predicate on the "service" field.
func ServiceNotIn(vs ...string) predicate.Price {
	return predicate.Price(sql.FieldNotIn(FieldService, vs...))
}

// ServiceGT applies the GT predicate on the "service" field.
func ServiceGT(v string) predicate.Price {
	return predicate.Price(sql.FieldGT(FieldService, v))
}

// ServiceGTE applies the GTE predicate on the "service" field.
func ServiceGTE(v string) predicate.Price {
	return predicate.Price(sql.FieldGTE(FieldService, v))
}

// ServiceLT applies the LT predicate on the "service" field.
func ServiceLT(v string) predicate.Price {
	return predicate.Price(sql.FieldLT(FieldService, v))
}

// ServiceLTE applies the LTE predicate on the "service" field.
func ServiceLTE(v string) predicate.Price {
	return predicate.Price(sql.FieldLTE(FieldService, v))
}

// ServiceContains applies the Contains predicate on the "service" field.
func ServiceContains(v string) predicate.Price {
	return predicate.Price(sql.FieldContains(FieldService, v))
}

// ServiceHasPrefix applies the HasPrefix predicate on the "service" field.
func ServiceHasPrefix(v string) predicate.Price {
	return predicate.Price(sql.FieldHasPrefix(FieldService, v))
}

// ServiceHasSuffix applies the HasSuffix predicate on the "service" field.
func ServiceHasSuffix(v string) predicate.Price {
	return predicate.Price(sql.FieldHasSuffix(FieldService, v))
}

// ServiceEqualFold applies the EqualFold predicate on the "service" field.
func ServiceEqualFold(v string) predicate.Price {
	return predicate.Price(sql.FieldEqualFold(FieldService, v))
}

// ServiceContainsFold applies the ContainsFold predicate on the "service" field.
func ServiceContainsFold(v string) predicate.Price {
	return predicate.Price(sql.FieldContainsFold(FieldService, v))
}

// ResourceTypeEQ applies the EQ predicate on the "resource_type" field.
func ResourceTypeEQ(v string) predicate.Price {
	return predicate.Price(sql.FieldEQ(FieldResourceType, v))
}

// ResourceTypeNEQ applies the NEQ predicate on the "resource_type" field.
func ResourceTypeNEQ(v string) predicate.Price {
	return predicate.Price(sql.FieldNEQ(FieldResourceType, v))
}

// ResourceTypeIn applies the In predicate on the "resource_type" field.
func ResourceTypeIn(vs ...string) predicate.Price {
	return predicate.Price(sql.FieldIn(FieldResourceType, vs...))
}

// ResourceTypeNotIn applies the NotIn predicate on the "resource_type" field.
func ResourceTypeNotIn(vs ...string) predicate.Price {
	return predicate.Price(sql.FieldNotIn(FieldResourceType, vs...))
}

// ResourceTypeGT applies the GT predicate on the "resource_type" field.
func ResourceTypeGT(v string) predicate.Price {
	return predicate.Price(sql.FieldGT(FieldResourceType, v))
}

// ResourceTypeGTE applies the GTE predicate on the "resource_type" field.
func ResourceTypeGTE(v string) predicate.Price {
	return predicate.Price(sql.FieldGTE(FieldResourceType, v))
}

// ResourceTypeLT applies the LT predicate on the "resource_type" field.
func ResourceTypeLT(v string) predicate.Price {
	return predicate.Price(sql.FieldLT(FieldResourceType, v))
}

// ResourceTypeLTE applies the LTE predicate on the "resource_type" field.
func ResourceTypeLTE(v string) predicate.Price {
	return predicate.Price(sql.FieldLTE(FieldResourceType, v))
}

// ResourceTypeContains applies the Contains predicate on the "resource_type" field.
func ResourceTypeContains(v string) predicate.Price {
	return predicate.Price(sql.FieldContains(FieldResourceType, v))
}

// ResourceTypeHasPrefix applies the HasPrefix predicate on the "resource_type" field.
func ResourceTypeHasPrefix(v string) predicate.Price {
	return predicate.Price(sql.FieldHasPrefix(FieldResourceType, v))
}

// ResourceTypeHasSuffix applies the HasSuffix predicate on the "resource_type" field.
func ResourceTypeHasSuffix(v string) predicate.Price {
	return predicate.Price(sql.FieldHasSuffix(FieldResourceType, v))
}

// ResourceTypeEqualFold applies the EqualFold predicate on the "resource_type" field.
func ResourceTypeEqualFold(v string) predicate.Price {
	return predicate.Price(sql.FieldEqualFold(FieldResourceType, v))
}

// ResourceTypeContainsFold applies the ContainsFold predicate on the "resource_type" field.
func ResourceTypeContainsFold(v string) predicate.Price {
	return predicate.Price(sql.FieldContainsFold(FieldResourceType, v))
}

// RegionEQ applies the EQ predicate on the "region" field.
func RegionEQ(v string) predicate.Price {
	return predicate.Price(sql.FieldEQ(FieldRegion, v))
}

// RegionNEQ applies the NEQ predicate on the "region" field.
func RegionNEQ(v string) predicate.Price {
	return predicate.Price(sql.FieldNEQ(FieldRegion, v))
}

// RegionIn applies the In predicate on the "region" field.
func RegionIn(vs ...string) predicate.Price {
	return predicate.Price(sql.FieldIn(FieldRegion, vs...))
}

// RegionNotIn applies the NotIn predicate on the "region" field.
func RegionNotIn(vs ...string) predicate.Price {
	return predicate.Price(sql.FieldNotIn(FieldRegion, vs...))
}

// RegionGT applies the GT predicate on the "region" field.
func RegionGT(v string) predicate.Price {
	return predicate.Price(sql.FieldGT(FieldRegion, v))
}

// RegionGTE applies the GTE predicate on the "region" field.
func RegionGTE(v string) predicate.Price {
	return predicate.Price(sql.FieldGTE(FieldRegion, v))
}

// RegionLT applies the LT predicate on the "region" field.
func RegionLT(v string) predicate.Price {
	return predicate.Price(sql.FieldLT(FieldRegion, v))
}

// RegionLTE applies the LTE predicate on the "region" field.
func RegionLTE(v string) predicate.Price {
	return predicate.Price(sql.FieldLTE(FieldRegion, v))
}

// RegionContains applies the Contains predicate on the "region" field.
func RegionContains(v string) predicate.Price {
	return predicate.Price(sql.FieldContains(FieldRegion, v))
}

// RegionHasPrefix applies the HasPrefix predicate on the "region" field.
func RegionHasPrefix(v string) predicate.Price {
	return predicate.Price(sql.FieldHasPrefix(FieldRegion, v))
}

// RegionHasSuffix applies the HasSuffix predicate on the "region" field.
func RegionHasSuffix(v string) predicate.Price {
	return predicate.Price(sql.FieldHasSuffix(FieldRegion, v))
}

// RegionEqualFold applies the EqualFold predicate on the "region" field.
func RegionEqualFold(v string) predicate.Price {
	return predicate.Price(sql.FieldEqualFold(FieldRegion, v))
}

// RegionContainsFold applies the ContainsFold predicate on the "region" field.
func RegionContainsFold(v string) predicate.Price {
	return predicate.Price(sql.FieldContainsFold(FieldRegion, v))
}

// PriceModelEQ applies the EQ predicate on the "price_model" field.
func PriceModelEQ(v string) predicate.Price {
	return predicate.Price(sql.FieldEQ(FieldPriceModel, v))
}

// PriceModelNEQ applies the NEQ predicate on the "price_model" field.
func PriceModelNEQ(v string) predicate.Price {
	return predicate.Price(sql.FieldNEQ(FieldPriceModel, v))
}

// PriceModelIn applies the In predicate on the "price_model" field.
func PriceModelIn(vs ...string) predicate.Price {
	return predicate.Price(sql.FieldIn(FieldPriceModel, vs...))
}

// PriceModelNotIn applies the NotIn predicate on the "price_model" field.
func PriceModelNotIn(vs ...string) predicate.Price {
	return predicate.Price(sql.FieldNotIn(FieldPriceModel, vs...))
}

// PriceModelGT applies the GT predicate on the "price_model" field.
func PriceModelGT(v string) predicate.Price {
	return predicate.Price(sql.FieldGT(FieldPriceModel, v))
}

// PriceModelGTE applies the GTE predicate on the "price_model" field.
func PriceModelGTE(v string) predicate.Price {
	return predicate.Price(sql.FieldGTE(FieldPriceModel, v))
}

// PriceModelLT applies the LT predicate on the "price_model" field.
func PriceModelLT(v string) predicate.Price {
	return predicate.Price(sql.FieldLT(FieldPriceModel, v))
}

// PriceModelLTE applies the LTE predicate on the "price_model" field.
func PriceModelLTE(v string) predicate.Price {
	return predicate.Price(sql.FieldLTE(FieldPriceModel, v))
}

// PriceModelContains applies the Contains predicate on the "price_model" field.
func PriceModelContains(v string) predicate.Price {
	return predicate.Price(sql.FieldContains(FieldPriceModel, v))
}

// PriceModelHasPrefix applies the HasPrefix predicate on the "price_model" field.
func PriceModelHasPrefix(v string) predicate.Price {
	return predicate.Price(sql.FieldHasPrefix(FieldPriceModel, v))
}

// PriceModelHasSuffix applies the HasSuffix predicate on the "price_model" field.
func PriceModelHasSuffix(v string) predicate.Price {
	return predicate.Price(sql.FieldHasSuffix(FieldPriceModel, v))
}

// PriceModelEqualFold applies the EqualFold predicate on the "price_model" field.
func PriceModelEqualFold(v string) predicate.Price {
	return predicate.Price(sql.FieldEqualFold(FieldPriceModel, v))
}

// PriceModelContainsFold applies the ContainsFold predicate on the "price_model" field.
func PriceModelContainsFold(v string) predicate.Price {
	return predicate.Price(sql.FieldContainsFold(FieldPriceModel, v))
}

// PricePerUnitEQ applies the EQ predicate on the "price_per_unit" field.
func PricePerUnitEQ(v float64) predicate.Price {
	return predicate.Price(sql.FieldEQ(FieldPricePerUnit, v))
}

// PricePerUnitNEQ applies the NEQ predicate on the "price_per_unit" field.
func PricePerUnitNEQ(v float64) predicate.Price {
	return predicate.Price(sql.FieldNEQ(FieldPricePerUnit, v))
}

// PricePerUnitIn applies the In predicate on the "price_per_unit" field.
func PricePerUnitIn(vs ...float64) predicate.Price {
	return predicate.Price(sql.FieldIn(FieldPricePerUnit, vs...))
}

// PricePerUnitNotIn applies the NotIn predicate on the "price_per_unit" field.
func PricePerUnitNotIn(vs ...float64) predicate.Price {
	return predicate.Price(sql.FieldNotIn(FieldPricePerUnit, vs...))
}

// PricePerUnitGT applies the GT predicate on the "price_per_unit" field.
func PricePerUnitGT(v float64) predicate.Price {
	return predicate.Price(sql.FieldGT(FieldPricePerUnit, v))
}

// PricePerUnitGTE applies the GTE predicate on the "price_per_unit" field.
func PricePerUnitGTE(v float64) predicate.Price {
	return predicate.Price(sql.FieldGTE(FieldPricePerUnit, v))
}

// PricePerUnitLT applies the LT predicate on the "price_per_unit" field.
func PricePerUnitLT(v float64) predicate.Price {
	return predicate.Price(sql.FieldLT(FieldPricePerUnit, v))
}

// PricePerUnitLTE applies the LTE predicate on the "price_per_unit" field.
func PricePerUnitLTE(v float64) predicate.Price {
	return predicate.Price(sql.FieldLTE(FieldPricePerUnit, v))
}

// UnitOfMeasureEQ applies the EQ predicate on the "unit_of_measure" field.
func UnitOfMeasureEQ(v string) predicate.Price {
	return predicate.Price(sql.FieldEQ(FieldUnitOfMeasure, v))
}

// UnitOfMeasureNEQ applies the NEQ predicate on the "unit_of_measure" field.
func UnitOfMeasureNEQ(v string) predicate.Price {
	return predicate.Price(sql.FieldNEQ(FieldUnitOfMeasure, v))
}

// UnitOfMeasureIn applies the In predicate on the "unit_of_measure" field.
func UnitOfMeasureIn(vs ...string) predicate.Price {
	return predicate.Price(sql.FieldIn(FieldUnitOfMeasure, vs...))
}

// UnitOfMeasureNotIn applies the NotIn predicate on the "unit_of_measure" field.
func UnitOfMeasureNotIn(vs ...string) predicate.Price {
	return predicate.Price(sql.FieldNotIn(FieldUnitOfMeasure, vs...))
}

// UnitOfMeasureGT applies the GT predicate on the "unit_of_measure" field.
func UnitOfMeasureGT(v string) predicate.Price {
	return predicate.Price(sql.FieldGT(FieldUnitOfMeasure, v))
}

// UnitOfMeasureGTE applies the GTE predicate on the "unit_of_measure" field.
func UnitOfMeasureGTE(v string) predicate.Price {
	return predicate.Price(sql.FieldGTE(FieldUnitOfMeasure, v))
}

// UnitOfMeasureLT applies the LT predicate on the "unit_of_measure" field.
func UnitOfMeasureLT(v string) predicate.Price {
	return predicate.Price(sql.FieldLT(FieldUnitOfMeasure, v))
}

// UnitOfMeasureLTE applies the LTE predicate on the "unit_of_measure" field.
func UnitOfMeasureLTE(v string) predicate.Price {
	return predicate.Price(sql.FieldLTE(FieldUnitOfMeasure, v))
}

// UnitOfMeasureContains applies the Contains predicate on the "unit_of_measure" field.
func UnitOfMeasureContains(v string) predicate.Price {
	return predicate.Price(sql.FieldContains(FieldUnitOfMeasure, v))
}

// UnitOfMeasureHasPrefix applies the HasPrefix predicate on the "unit_of_measure" field.
func UnitOfMeasureHasPrefix(v string) predicate.Price {
	return predicate.Price(sql.FieldHasPrefix(FieldUnitOfMeasure, v))
}

// UnitOfMeasureHasSuffix applies the HasSuffix predicate on the "unit_of_measure" field.
func UnitOfMeasureHasSuffix(v string) predicate.Price {
	return predicate.Price(sql.FieldHasSuffix(FieldUnitOfMeasure, v))
}

// UnitOfMeasureEqualFold applies the EqualFold predicate on the "unit_of_measure" field.
func UnitOfMeasureEqualFold(v string) predicate.Price {
	return predicate.Price(sql.FieldEqualFold(FieldUnitOfMeasure, v))
}

// UnitOfMeasureContainsFold applies the ContainsFold predicate on the "unit_of_measure" field.
func UnitOfMeasureContainsFold(v string) predicate.Price {
	return predicate.Price(sql.FieldContainsFold(FieldUnitOfMeasure, v))
}

// UpfrontCostEQ applies the EQ predicate on the "upfront_cost" field.
func UpfrontCostEQ(v float64) predicate.Price {
	return predicate.Price(sql.FieldEQ(FieldUpfrontCost, v))
}

// UpfrontCostNEQ applies the NEQ predicate on the "upfront_cost" field.
func UpfrontCostNEQ(v float64) predicate.Price {
	return predicate.Price(sql.FieldNEQ(FieldUpfrontCost, v))
}

// UpfrontCostIn applies the In predicate on the "upfront_cost" field.
func UpfrontCostIn(vs ...float64) predicate.Price {
	return predicate.Price(sql.FieldIn(FieldUpfrontCost, vs...))
}

// UpfrontCostNotIn applies the NotIn predicate on the "upfront_cost" field.
func UpfrontCostNotIn(vs ...float64) predicate.Price {
	return predicate.Price(sql.FieldNotIn(FieldUpfrontCost, vs...))
}

// UpfrontCostGT applies the GT predicate on the "upfront_cost" field.
func UpfrontCostGT(v float64) predicate.Price {
	return predicate.Price(sql.FieldGT(FieldUpfrontCost, v))
}

// UpfrontCostGTE applies the GTE predicate on the "upfront_cost" field.
func UpfrontCostGTE(v float64) predicate.Price {
	return predicate.Price(sql.FieldGTE(FieldUpfrontCost, v))
}

// UpfrontCostLT applies the LT predicate on the "upfront_cost" field.
func UpfrontCostLT(v float64) predicate.Price {
	return predicate.Price(sql.FieldLT(FieldUpfrontCost, v))
}

// UpfrontCostLTE applies the LTE predicate on the "upfront_cost" field.
func UpfrontCostLTE(v float64) predicate.Price {
	return predicate.Price(sql.FieldLTE(FieldUpfrontCost, v))
}

// UpfrontCostIsNil applies the IsNil predicate on the "upfront_cost" field.
func UpfrontCostIsNil() predicate.Price {
	return predicate.Price(sql.FieldIsNull(FieldUpfrontCost))
}

// UpfrontCostNotNil applies the NotNil predicate on the "upfront_cost" field.
func UpfrontCostNotNil() predicate.Price {
	return predicate.Price(sql.FieldNotNull(FieldUpfrontCost))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.Price {
	return predicate.Price(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.Price {
	return predicate.Price(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.Price {
	return predicate.Price(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.Price {
	return predicate.Price(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.Price {
	return predicate.Price(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.Price {
	return predicate.Price(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.Price {
	return predicate.Price(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.Price {
	return predicate.Price(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.Price {
	return predicate.Price(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.Price {
	return predicate.Price(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.Price {
	return predicate.Price(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.Price {
	return predicate.Price(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.Price {
	return predicate.Price(sql.FieldContainsFold(FieldCurrency, v))
}

// LastUpdatedAtEQ applies the EQ predicate on the "last_updated_at" field.
func LastUpdatedAtEQ(v time.Time) predicate.Price {
	return predicate.Price(sql.FieldEQ(FieldLastUpdatedAt, v))
}

// LastUpdatedAtNEQ applies the NEQ predicate on the "last_updated_at" field.
func LastUpdatedAtNEQ(v time.Time) predicate.Price {
	return predicate.Price(sql.FieldNEQ(FieldLastUpdatedAt, v))
}

// LastUpdatedAtIn applies the In predicate on the "last_updated_at" field.
func LastUpdatedAtIn(vs ...time.Time) predicate.Price {
	return predicate.Price(sql.FieldIn(FieldLastUpdatedAt, vs...))
}

// LastUpdatedAtNotIn applies the NotIn predicate on the "last_updated_at" field.
func LastUpdatedAtNotIn(vs ...time.Time) predicate.Price {
	return predicate.Price(sql.FieldNotIn(FieldLastUpdatedAt, vs...))
}

// LastUpdatedAtGT applies the GT predicate on the "last_updated_at" field.
func LastUpdatedAtGT(v time.Time) predicate.Price {
	return predicate.Price(sql.FieldGT(FieldLastUpdatedAt, v))
}

// LastUpdatedAtGTE applies the GTE predicate on the "last_updated_at" field.
func LastUpdatedAtGTE(v time.Time) predicate.Price {
	return predicate.Price(sql.FieldGTE(FieldLastUpdatedAt, v))
}

// LastUpdatedAtLT applies the LT predicate on the "last_updated_at" field.
func LastUpdatedAtLT(v time.Time) predicate.Price {
	return predicate.Price(sql.FieldLT(FieldLastUpdatedAt, v))
}

// LastUpdatedAtLTE applies the LTE predicate on the "last_updated_at" field.
func LastUpdatedAtLTE(v time.Time) predicate.Price {
	return predicate.Price(sql.FieldLTE(FieldLastUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Price) predicate.Price {
	return predicate.Price(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Price) predicate.Price {
	return predicate.Price(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Price) predicate.Price {
	return predicate.Price(sql.NotPredicates(p))
}
