// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"priceyy/api/ent/predicate"
	"priceyy/api/ent/price"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PriceUpdate is the builder for updating Price entities.
type PriceUpdate struct {
	config
	hooks    []Hook
	mutation *PriceMutation
}

// Where appends a list predicates to the PriceUpdate builder.
func (_u *PriceUpdate) Where(ps ...predicate.Price) *PriceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *PriceUpdate) SetProvider(v string) *PriceUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *PriceUpdate) SetNillableProvider(v *string) *PriceUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetService sets the "service" field.
func (_u *PriceUpdate) SetService(v string) *PriceUpdate {
	_u.mutation.SetService(v)
	return _u
}

// SetNillableService sets the "service" field if the given value is not nil.
func (_u *PriceUpdate) SetNillableService(v *string) *PriceUpdate {
	if v != nil {
		_u.SetService(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *PriceUpdate) SetResourceType(v string) *PriceUpdate {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *PriceUpdate) SetNillableResourceType(v *string) *PriceUpdate {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *PriceUpdate) SetRegion(v string) *PriceUpdate {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *PriceUpdate) SetNillableRegion(v *string) *PriceUpdate {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetPriceModel sets the "price_model" field.
func (_u *PriceUpdate) SetPriceModel(v string) *PriceUpdate {
	_u.mutation.SetPriceModel(v)
	return _u
}

// SetNillablePriceModel sets the "price_model" field if the given value is not nil.
func (_u *PriceUpdate) SetNillablePriceModel(v *string) *PriceUpdate {
	if v != nil {
		_u.SetPriceModel(*v)
	}
	return _u
}

// SetPricePerUnit sets the "price_per_unit" field.
func (_u *PriceUpdate) SetPricePerUnit(v float64) *PriceUpdate {
	_u.mutation.ResetPricePerUnit()
	_u.mutation.SetPricePerUnit(v)
	return _u
}

// SetNillablePricePerUnit sets the "price_per_unit" field if the given value is not nil.
func (_u *PriceUpdate) SetNillablePricePerUnit(v *float64) *PriceUpdate {
	if v != nil {
		_u.SetPricePerUnit(*v)
	}
	return _u
}

// AddPricePerUnit adds value to the "price_per_unit" field.
func (_u *PriceUpdate) AddPricePerUnit(v float64) *PriceUpdate {
	_u.mutation.AddPricePerUnit(v)
	return _u
}

// SetUnitOfMeasure sets the "unit_of_measure" field.
func (_u *PriceUpdate) SetUnitOfMeasure(v string) *PriceUpdate {
	_u.mutation.SetUnitOfMeasure(v)
	return _u
}

// SetNillableUnitOfMeasure sets the "unit_of_measure" field if the given value is not nil.
func (_u *PriceUpdate) SetNillableUnitOfMeasure(v *string) *PriceUpdate {
	if v != nil {
		_u.SetUnitOfMeasure(*v)
	}
	return _u
}

// SetUpfrontCost sets the "upfront_cost" field.
func (_u *PriceUpdate) SetUpfrontCost(v float64) *PriceUpdate {
	_u.mutation.ResetUpfrontCost()
	_u.mutation.SetUpfrontCost(v)
	return _u
}

// SetNillableUpfrontCost sets the "upfront_cost" field if the given value is not nil.
func (_u *PriceUpdate) SetNillableUpfrontCost(v *float64) *PriceUpdate {
	if v != nil {
		_u.SetUpfrontCost(*v)
	}
	return _u
}

// AddUpfrontCost adds value to the "upfront_cost" field.
func (_u *PriceUpdate) AddUpfrontCost(v float64) *PriceUpdate {
	_u.mutation.AddUpfrontCost(v)
	return _u
}

// ClearUpfrontCost clears the value of the "upfront_cost" field.
func (_u *PriceUpdate) ClearUpfrontCost() *PriceUpdate {
	_u.mutation.ClearUpfrontCost()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PriceUpdate) SetCurrency(v string) *PriceUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PriceUpdate) SetNillableCurrency(v *string) *PriceUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetLastUpdatedAt sets the "last_updated_at" field.
func (_u *PriceUpdate) SetLastUpdatedAt(v time.Time) *PriceUpdate {
	_u.mutation.SetLastUpdatedAt(v)
	return _u
}

// Mutation returns the PriceMutation object of the builder.
func (_u *PriceUpdate) Mutation() *PriceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PriceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PriceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PriceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PriceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PriceUpdate) defaults() {
	if _, ok := _u.mutation.LastUpdatedAt(); !ok {
		v := price.UpdateDefaultLastUpdatedAt()
		_u.mutation.SetLastUpdatedAt(v)
	}
}

func (_u *PriceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(price.Table, price.Columns, sqlgraph.NewFieldSpec(price.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(price.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Service(); ok {
		_spec.SetField(price.FieldService, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(price.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(price.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.PriceModel(); ok {
		_spec.SetField(price.FieldPriceModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.PricePerUnit(); ok {
		_spec.SetField(price.FieldPricePerUnit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPricePerUnit(); ok {
		_spec.AddField(price.FieldPricePerUnit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UnitOfMeasure(); ok {
		_spec.SetField(price.FieldUnitOfMeasure, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpfrontCost(); ok {
		_spec.SetField(price.FieldUpfrontCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUpfrontCost(); ok {
		_spec.AddField(price.FieldUpfrontCost, field.TypeFloat64, value)
	}
	if _u.mutation.UpfrontCostCleared() {
		_spec.ClearField(price.FieldUpfrontCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(price.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastUpdatedAt(); ok {
		_spec.SetField(price.FieldLastUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{price.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PriceUpdateOne is the builder for updating a single Price entity.
type PriceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PriceMutation
}

// SetProvider sets the "provider" field.
func (_u *PriceUpdateOne) SetProvider(v string) *PriceUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *PriceUpdateOne) SetNillableProvider(v *string) *PriceUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetService sets the "service" field.
func (_u *PriceUpdateOne) SetService(v string) *PriceUpdateOne {
	_u.mutation.SetService(v)
	return _u
}

// SetNillableService sets the "service" field if the given value is not nil.
func (_u *PriceUpdateOne) SetNillableService(v *string) *PriceUpdateOne {
	if v != nil {
		_u.SetService(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *PriceUpdateOne) SetResourceType(v string) *PriceUpdateOne {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *PriceUpdateOne) SetNillableResourceType(v *string) *PriceUpdateOne {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *PriceUpdateOne) SetRegion(v string) *PriceUpdateOne {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *PriceUpdateOne) SetNillableRegion(v *string) *PriceUpdateOne {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetPriceModel sets the "price_model" field.
func (_u *PriceUpdateOne) SetPriceModel(v string) *PriceUpdateOne {
	_u.mutation.SetPriceModel(v)
	return _u
}

// SetNillablePriceModel sets the "price_model" field if the given value is not nil.
func (_u *PriceUpdateOne) SetNillablePriceModel(v *string) *PriceUpdateOne {
	if v != nil {
		_u.SetPriceModel(*v)
	}
	return _u
}

// SetPricePerUnit sets the "price_per_unit" field.
func (_u *PriceUpdateOne) SetPricePerUnit(v float64) *PriceUpdateOne {
	_u.mutation.ResetPricePerUnit()
	_u.mutation.SetPricePerUnit(v)
	return _u
}

// SetNillablePricePerUnit sets the "price_per_unit" field if the given value is not nil.
func (_u *PriceUpdateOne) SetNillablePricePerUnit(v *float64) *PriceUpdateOne {
	if v != nil {
		_u.SetPricePerUnit(*v)
	}
	return _u
}

// AddPricePerUnit adds value to the "price_per_unit" field.
func (_u *PriceUpdateOne) AddPricePerUnit(v float64) *PriceUpdateOne {
	_u.mutation.AddPricePerUnit(v)
	return _u
}

// SetUnitOfMeasure sets the "unit_of_measure" field.
func (_u *PriceUpdateOne) SetUnitOfMeasure(v string) *PriceUpdateOne {
	_u.mutation.SetUnitOfMeasure(v)
	return _u
}

// SetNillableUnitOfMeasure sets the "unit_of_measure" field if the given value is not nil.
func (_u *PriceUpdateOne) SetNillableUnitOfMeasure(v *string) *PriceUpdateOne {
	if v != nil {
		_u.SetUnitOfMeasure(*v)
	}
	return _u
}

// SetUpfrontCost sets the "upfront_cost" field.
func (_u *PriceUpdateOne) SetUpfrontCost(v float64) *PriceUpdateOne {
	_u.mutation.ResetUpfrontCost()
	_u.mutation.SetUpfrontCost(v)
	return _u
}

// SetNillableUpfrontCost sets the "upfront_cost" field if the given value is not nil.
func (_u *PriceUpdateOne) SetNillableUpfrontCost(v *float64) *PriceUpdateOne {
	if v != nil {
		_u.SetUpfrontCost(*v)
	}
	return _u
}

// AddUpfrontCost adds value to the "upfront_cost" field.
func (_u *PriceUpdateOne) AddUpfrontCost(v float64) *PriceUpdateOne {
	_u.mutation.AddUpfrontCost(v)
	return _u
}

// ClearUpfrontCost clears the value of the "upfront_cost" field.
func (_u *PriceUpdateOne) ClearUpfrontCost() *PriceUpdateOne {
	_u.mutation.ClearUpfrontCost()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PriceUpdateOne) SetCurrency(v string) *PriceUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PriceUpdateOne) SetNillableCurrency(v *string) *PriceUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetLastUpdatedAt sets the "last_updated_at" field.
func (_u *PriceUpdateOne) SetLastUpdatedAt(v time.Time) *PriceUpdateOne {
	_u.mutation.SetLastUpdatedAt(v)
	return _u
}

// Mutation returns the PriceMutation object of the builder.
func (_u *PriceUpdateOne) Mutation() *PriceMutation {
	return _u.mutation
}

// Where appends a list predicates to the PriceUpdate builder.
func (_u *PriceUpdateOne) Where(ps ...predicate.Price) *PriceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PriceUpdateOne) Select(field string, fields ...string) *PriceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Price entity.
func (_u *PriceUpdateOne) Save(ctx context.Context) (*Price, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PriceUpdateOne) SaveX(ctx context.Context) *Price {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PriceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PriceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PriceUpdateOne) defaults() {
	if _, ok := _u.mutation.LastUpdatedAt(); !ok {
		v := price.UpdateDefaultLastUpdatedAt()
		_u.mutation.SetLastUpdatedAt(v)
	}
}

func (_u *PriceUpdateOne) sqlSave(ctx context.Context) (_node *Price, err error) {
	_spec := sqlgraph.NewUpdateSpec(price.Table, price.Columns, sqlgraph.NewFieldSpec(price.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Price.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, price.FieldID)
		for _, f := range fields {
			if !price.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != price.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(price.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Service(); ok {
		_spec.SetField(price.FieldService, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(price.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(price.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.PriceModel(); ok {
		_spec.SetField(price.FieldPriceModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.PricePerUnit(); ok {
		_spec.SetField(price.FieldPricePerUnit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPricePerUnit(); ok {
		_spec.AddField(price.FieldPricePerUnit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UnitOfMeasure(); ok {
		_spec.SetField(price.FieldUnitOfMeasure, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpfrontCost(); ok {
		_spec.SetField(price.FieldUpfrontCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUpfrontCost(); ok {
		_spec.AddField(price.FieldUpfrontCost, field.TypeFloat64, value)
	}
	if _u.mutation.UpfrontCostCleared() {
		_spec.ClearField(price.FieldUpfrontCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(price.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastUpdatedAt(); ok {
		_spec.SetField(price.FieldLastUpdatedAt, field.TypeTime, value)
	}
	_node = &Price{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{price.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
