// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"priceyy/api/ent/price"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PriceCreate is the builder for creating a Price entity.
type PriceCreate struct {
	config
	mutation *PriceMutation
	hooks    []Hook
}

// SetProvider sets the "provider" field.
func (_c *PriceCreate) SetProvider(v string) *PriceCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetService sets the "service" field.
func (_c *PriceCreate) SetService(v string) *PriceCreate {
	_c.mutation.SetService(v)
	return _c
}

// SetResourceType sets the "resource_type" field.
func (_c *PriceCreate) SetResourceType(v string) *PriceCreate {
	_c.mutation.SetResourceType(v)
	return _c
}

// SetRegion sets the "region" field.
func (_c *PriceCreate) SetRegion(v string) *PriceCreate {
	_c.mutation.SetRegion(v)
	return _c
}

// SetPriceModel sets the "price_model" field.
func (_c *PriceCreate) SetPriceModel(v string) *PriceCreate {
	_c.mutation.SetPriceModel(v)
	return _c
}

// SetPricePerHour sets the "price_per_hour" field.
func (_c *PriceCreate) SetPricePerHour(v float64) *PriceCreate {
	_c.mutation.SetPricePerHour(v)
	return _c
}

// SetUpfrontCost sets the "upfront_cost" field.
func (_c *PriceCreate) SetUpfrontCost(v float64) *PriceCreate {
	_c.mutation.SetUpfrontCost(v)
	return _c
}

// SetNillableUpfrontCost sets the "upfront_cost" field if the given value is not nil.
func (_c *PriceCreate) SetNillableUpfrontCost(v *float64) *PriceCreate {
	if v != nil {
		_c.SetUpfrontCost(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *PriceCreate) SetCurrency(v string) *PriceCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *PriceCreate) SetNillableCurrency(v *string) *PriceCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetLastUpdatedAt sets the "last_updated_at" field.
func (_c *PriceCreate) SetLastUpdatedAt(v time.Time) *PriceCreate {
	_c.mutation.SetLastUpdatedAt(v)
	return _c
}

// SetNillableLastUpdatedAt sets the "last_updated_at" field if the given value is not nil.
func (_c *PriceCreate) SetNillableLastUpdatedAt(v *time.Time) *PriceCreate {
	if v != nil {
		_c.SetLastUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PriceCreate) SetID(v uuid.UUID) *PriceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PriceCreate) SetNillableID(v *uuid.UUID) *PriceCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the PriceMutation object of the builder.
func (_c *PriceCreate) Mutation() *PriceMutation {
	return _c.mutation
}

// Save creates the Price in the database.
func (_c *PriceCreate) Save(ctx context.Context) (*Price, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PriceCreate) SaveX(ctx context.Context) *Price {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PriceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PriceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PriceCreate) defaults() {
	if _, ok := _c.mutation.Currency(); !ok {
		v := price.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.LastUpdatedAt(); !ok {
		v := price.DefaultLastUpdatedAt()
		_c.mutation.SetLastUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := price.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PriceCreate) check() error {
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "Price.provider"`)}
	}
	if _, ok := _c.mutation.Service(); !ok {
		return &ValidationError{Name: "service", err: errors.New(`ent: missing required field "Price.service"`)}
	}
	if _, ok := _c.mutation.ResourceType(); !ok {
		return &ValidationError{Name: "resource_type", err: errors.New(`ent: missing required field "Price.resource_type"`)}
	}
	if _, ok := _c.mutation.Region(); !ok {
		return &ValidationError{Name: "region", err: errors.New(`ent: missing required field "Price.region"`)}
	}
	if _, ok := _c.mutation.PriceModel(); !ok {
		return &ValidationError{Name: "price_model", err: errors.New(`ent: missing required field "Price.price_model"`)}
	}
	if _, ok := _c.mutation.PricePerHour(); !ok {
		return &ValidationError{Name: "price_per_hour", err: errors.New(`ent: missing required field "Price.price_per_hour"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Price.currency"`)}
	}
	if _, ok := _c.mutation.LastUpdatedAt(); !ok {
		return &ValidationError{Name: "last_updated_at", err: errors.New(`ent: missing required field "Price.last_updated_at"`)}
	}
	return nil
}

func (_c *PriceCreate) sqlSave(ctx context.Context) (*Price, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PriceCreate) createSpec() (*Price, *sqlgraph.CreateSpec) {
	var (
		_node = &Price{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(price.Table, sqlgraph.NewFieldSpec(price.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(price.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Service(); ok {
		_spec.SetField(price.FieldService, field.TypeString, value)
		_node.Service = value
	}
	if value, ok := _c.mutation.ResourceType(); ok {
		_spec.SetField(price.FieldResourceType, field.TypeString, value)
		_node.ResourceType = value
	}
	if value, ok := _c.mutation.Region(); ok {
		_spec.SetField(price.FieldRegion, field.TypeString, value)
		_node.Region = value
	}
	if value, ok := _c.mutation.PriceModel(); ok {
		_spec.SetField(price.FieldPriceModel, field.TypeString, value)
		_node.PriceModel = value
	}
	if value, ok := _c.mutation.PricePerHour(); ok {
		_spec.SetField(price.FieldPricePerHour, field.TypeFloat64, value)
		_node.PricePerHour = value
	}
	if value, ok := _c.mutation.UpfrontCost(); ok {
		_spec.SetField(price.FieldUpfrontCost, field.TypeFloat64, value)
		_node.UpfrontCost = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(price.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.LastUpdatedAt(); ok {
		_spec.SetField(price.FieldLastUpdatedAt, field.TypeTime, value)
		_node.LastUpdatedAt = value
	}
	return _node, _spec
}

// PriceCreateBulk is the builder for creating many Price entities in bulk.
type PriceCreateBulk struct {
	config
	err      error
	builders []*PriceCreate
}

// Save creates the Price entities in the database.
func (_c *PriceCreateBulk) Save(ctx context.Context) ([]*Price, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Price, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PriceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PriceCreateBulk) SaveX(ctx context.Context) []*Price {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PriceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PriceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
