// Code generated by ent, DO NOT EDIT.

package ent

import (
	"priceyy/api/ent/price"
	"priceyy/api/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	priceFields := schema.Price{}.Fields()
	_ = priceFields
	// priceDescCurrency is the schema descriptor for currency field.
	priceDescCurrency := priceFields[9].Descriptor()
	// price.DefaultCurrency holds the default value on creation for the currency field.
	price.DefaultCurrency = priceDescCurrency.Default.(string)
	// priceDescLastUpdatedAt is the schema descriptor for last_updated_at field.
	priceDescLastUpdatedAt := priceFields[10].Descriptor()
	// price.DefaultLastUpdatedAt holds the default value on creation for the last_updated_at field.
	price.DefaultLastUpdatedAt = priceDescLastUpdatedAt.Default.(func() time.Time)
	// price.UpdateDefaultLastUpdatedAt holds the default value on update for the last_updated_at field.
	price.UpdateDefaultLastUpdatedAt = priceDescLastUpdatedAt.UpdateDefault.(func() time.Time)
	// priceDescID is the schema descriptor for id field.
	priceDescID := priceFields[0].Descriptor()
	// price.DefaultID holds the default value on creation for the id field.
	price.DefaultID = priceDescID.Default.(func() uuid.UUID)
}
