// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PricesColumns holds the columns for the "prices" table.
	PricesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "provider", Type: field.TypeString},
		{Name: "service", Type: field.TypeString},
		{Name: "resource_type", Type: field.TypeString},
		{Name: "region", Type: field.TypeString},
		{Name: "price_model", Type: field.TypeString},
		{Name: "price_per_hour", Type: field.TypeFloat64},
		{Name: "upfront_cost", Type: field.TypeFloat64, Nullable: true},
		{Name: "currency", Type: field.TypeString, Default: "USD"},
		{Name: "last_updated_at", Type: field.TypeTime},
	}
	// PricesTable holds the schema information for the "prices" table.
	PricesTable = &schema.Table{
		Name:       "prices",
		Columns:    PricesColumns,
		PrimaryKey: []*schema.Column{PricesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "price_provider_resource_type_region_price_model",
				Unique:  true,
				Columns: []*schema.Column{PricesColumns[1], PricesColumns[3], PricesColumns[4], PricesColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PricesTable,
	}
)

func init() {
}
