import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

// Mappage complet et robuste basé sur les données réelles de l'API.
export const regionToCountryCode: Record<string, string> = {
  // === AWS Regions (Human-readable names) ===
  "africa (cape town)": "ZA",
  "argentina (buenos aires)": "AR",
  "asia pacific (hong kong)": "HK",
  "asia pacific (hyderabad)": "IN",
  "asia pacific (jakarta)": "ID",
  "asia pacific (kddi) - osaka": "JP",
  "asia pacific (kddi) - tokyo": "JP",
  "asia pacific (malaysia)": "MY",
  "asia pacific (melbourne)": "AU",
  "asia pacific (mumbai)": "IN",
  "asia pacific (new zealand)": "NZ",
  "asia pacific (osaka)": "JP",
  "asia pacific (skt) - daejeon": "KR",
  "asia pacific (skt) - seoul": "KR",
  "asia pacific (seoul)": "KR",
  "asia pacific (singapore)": "SG",
  "asia pacific (sydney)": "AU",
  "asia pacific (taipei)": "TW",
  "asia pacific (thailand)": "TH",
  "asia pacific (tokyo)": "JP",
  "australia (perth)": "AU",
  "canada (bell) - toronto": "CA",
  "canada (central)": "CA",
  "canada west (calgary)": "CA",
  "chile (santiago)": "CL",
  "denmark (copenhagen)": "DK",
  "eu (frankfurt)": "DE",
  "eu (ireland)": "IE",
  "eu (london)": "GB",
  "eu (milan)": "IT",
  "eu (paris)": "FR",
  "eu (stockholm)": "SE",
  "europe (british telecom) - manchester": "GB",
  "europe (spain)": "ES",
  "europe (vodafone) - berlin": "DE",
  "europe (vodafone) - dortmund": "DE",
  "europe (vodafone) - london": "GB",
  "europe (vodafone) - manchester": "GB",
  "europe (vodafone) - munich": "DE",
  "europe (zurich)": "CH",
  "finland (helsinki)": "FI",
  "germany (hamburg)": "DE",
  "india (delhi)": "IN",
  "india (kolkata)": "IN",
  "israel (tel aviv)": "IL",
  "mexico (central)": "MX",
  "mexico (queretaro)": "MX",
  "middle east (bahrain)": "BH",
  "middle east (uae)": "AE",
  "morocco (casablanca)": "MA",
  "new zealand (auckland)": "NZ",
  "nigeria (lagos)": "NG",
  "oman (muscat)": "OM",
  "peru (lima)": "PE",
  "philippines (manila)": "PH",
  "poland (warsaw)": "PL",
  "senegal (dakar)": "SN",
  "south america (sao paulo)": "BR",
  "us east (n. virginia)": "US",
  "us east (ohio)": "US",
  "us west (n. california)": "US",
  "us west (oregon)": "US",
  "us east (atlanta)": "US",
  "us east (boston)": "US",
  "us east (chicago)": "US",
  "us east (dallas)": "US",
  "us east (houston)": "US",
  "us east (kansas city 2)": "US",
  "us east (lenexa)": "US",
  "us east (miami)": "US",
  "us east (minneapolis)": "US",
  "us east (new york city)": "US",
  "us east (philadelphia)": "US",
  "us west (denver)": "US",
  "us west (honolulu)": "US",
  "us west (las vegas)": "US",
  "us west (los angeles)": "US",
  "us west (phoenix)": "US",
  "us west (portland)": "US",
  "us west (seattle)": "US",
  "aws govcloud (us-east)": "US",
  "aws govcloud (us-west)": "US",

  // === Azure Regions (Codename style) ===
  australiacentral: "AU",
  australiacentral2: "AU",
  australiaeast: "AU",
  australiasoutheast: "AU",
  perth: "AU",
  austriaeast: "AT",
  belgiumcentral: "BE",
  brazilsouth: "BR",
  brazilsoutheast: "BR",
  canadacentral: "CA",
  canadaeast: "CA",
  centralindia: "IN",
  jioindiacentral: "IN",
  jioindiawest: "IN",
  southindia: "IN",
  westindia: "IN",
  centralus: "US",
  eastus: "US",
  eastus2: "US",
  northcentralus: "US",
  southcentralus: "US",
  westus: "US",
  westus2: "US",
  westus3: "US",
  westcentralus: "US",
  southcentralus2: "US",
  southeastus: "US",
  southwestus: "US",
  usgovarizona: "US",
  usgoviowa: "US",
  usgovtexas: "US",
  usgovvirginia: "US",
  "azure stack us gov": "US",
  chilecentral: "CL",
  denmarkeast: "DK",
  eastasia: "HK",
  southeastasia: "SG",
  francecentral: "FR",
  francesouth: "FR",
  germanynorth: "DE",
  germanywestcentral: "DE",
  deloscloudgermanycentral: "DE",
  deloscloudgermanynorth: "DE",
  indonesiacentral: "ID",
  israelcentral: "IL",
  israelnorthwest: "IL",
  italynorth: "IT",
  japaneast: "JP",
  japanwest: "JP",
  koreacentral: "KR",
  koreasouth: "KR",
  malaysiasouth: "MY",
  malaysiawest: "MY",
  mexicocentral: "MX",
  newzealandnorth: "NZ",
  northeurope: "IE",
  westeurope: "NL",
  norwayeast: "NO",
  norwaywest: "NO",
  polandcentral: "PL",
  qatarcentral: "QA",
  southafricanorth: "ZA",
  southafricawest: "ZA",
  spaincentral: "ES",
  swedencentral: "SE",
  swedensouth: "SE",
  switzerlandnorth: "CH",
  switzerlandwest: "CH",
  taiwannorth: "TW",
  taiwannorthwest: "TW",
  uaecentral: "AE",
  uaenorth: "AE",
  uksouth: "GB",
  ukwest: "GB",

  // === GCP Regions (Codename style) ===
  "africa-south1": "ZA",
  "asia-east1": "TW",
  "asia-east2": "HK",
  "asia-northeast1": "JP",
  "asia-northeast2": "JP",
  "asia-northeast3": "KR",
  "asia-south1": "IN",
  "asia-south2": "IN",
  "asia-southeast1": "SG",
  "asia-southeast2": "ID",
  "australia-southeast1": "AU",
  "australia-southeast2": "AU",
  "europe-central2": "PL",
  "europe-north1": "FI",
  "europe-southwest1": "ES",
  "europe-west1": "BE",
  "europe-west2": "GB",
  "europe-west3": "DE",
  "europe-west4": "NL",
  "europe-west6": "CH",
  "europe-west8": "IT",
  "europe-west9": "FR",
  "europe-west10": "DE",
  "europe-west12": "IT",
  "me-central1": "QA",
  "me-central2": "SA",
  "me-west1": "IL",
  "northamerica-northeast1": "CA",
  "northamerica-northeast2": "CA",
  "southamerica-east1": "BR",
  "southamerica-west1": "CL",
  "us-central1": "US",
  "us-east1": "US",
  "us-east4": "US",
  "us-east5": "US",
  "us-west1": "US",
  "us-west2": "US",
  "us-west3": "US",
  "us-west4": "US",
  "us-west5": "US",
  "us-west6": "US",
  "us-west7": "US",
  "us-west8": "US",
  "us-east7": "US",
  "us-east8": "US",
  "us-east9": "US",
  "us-south1": "US",
};
